### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by edsu** [sul-dlss/was-pywb#12]
We need to be able to track access to the new swap.stanford.edu, which means adding the tracking code and JavaScript to the pywb templates.  We can copy/paste the following JavaScript into the pywb header template.

```html
    <script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
	
	  ga('create', 'UA-7219229-29', 'auto');
	  ga('send', 'pageview');
	</script>
```

Update the checklist in DevOpsDocs for was-pywb to indicate that it is being tracked.

**Comment by mjgiarlo** [comment]
It would be useful to determine if it's OK to turn this on in all environments or better to only turn it on in production.

**Comment by mjgiarlo** [comment]
> * [ ]  Determine if it's OK to turn this on in all environments or better to only turn it on in production

@edsu @aaron-collier do y'all have thoughts on ☝🏻 ? Not needed?

**Comment by edsu** [comment]
In the end I guess I fell on the side of not worrying if our metrics are inflated a bit by qa/stage testing. But are there other potential side effects?
