### ISSUE TITLE
Playback quality testing

### ISSUE THREAD

**Issue by edsu** [sul-dlss/was-pywb#14]
Once the full content is available on was-pywb-prod we should work with Peter Chan to evaluate the playback quality to see if problematic content that plays well in Archive-It is improved.

**Comment by peterchanws** [comment]
Fine at Archive-IT
https://wayback.archive-it.org/14708/20200803204442/https://www.patreon.com/davidwolinsky/

Still have problem in pywb
https://was-pywb-prod.stanford.edu/was/20200803204442/https://www.patreon.com/davidwolinsky

**Comment by peterchanws** [comment]
Fine at Archive-IT (under Safari but not Chrome)
https://wayback.archive-it.org/6385/20200724194832/http://reaisjogosvirtuais.blogspot.com/

Still have problem in pywb (both Safari and Chrome)
https://was-pywb-prod.stanford.edu/was/20200724195034/http://reaisjogosvirtuais.blogspot.com/

**Comment by peterchanws** [comment]
For this site, the banner for SWAP cover the dropdown menu for the site
https://swap.stanford.edu/20210128000826/https://www.theaaas2020project.com/about

No problem yet for pywb
https://was-pywb-prod.stanford.edu/was/20210128000826/https://www.theaaas2020project.com/about

However, I am afraid the same issue will occur when we add SWAP banner in pywb. Should I open a new issue for that?

**Comment by edsu** [comment]
I do think we need an issue ticket for what to do about the "item view". I personally think we'll want to be careful about adding too much, which could interfere and distract from the archived content that users want to see. But providing navigation to the homepage, and adequate context for what is being viewed seem important?

**Comment by lwrubel** [comment]
The pywb banner does not cover the replay, so even though we're implementing with parity in mind, I don't think that will go as far as recreating this problem.

**Comment by peterchanws** [comment]
The video itself will play through the Archive-IT banners' Lightbox media player but not via the YouTube's play back controls. Archive-IT know the issue and is working on that.
https://wayback.archive-it.org/13612/20200708220803if_/https://www.youtube.com/watch?v=ONhnEmoSRfk

However, since we don't have a banner and thus no media player control, I can't play the video in pywb.
https://was-pywb-prod.stanford.edu/was/20200708220803/https://www.youtube.com/watch?v=ONhnEmoSRfk

**Comment by peterchanws** [comment]
Another example of improved rendering:

https://swap.stanford.edu/20170527002349/http://jeanlassalle2017.fr/
https://was-pywb-prod.stanford.edu/was/20170527002349/http://jeanlassalle2017.fr/

**Comment by peterchanws** [comment]
This example show more control in rendering PDF document

https://swap.stanford.edu/20211109210723/https://documents2.theblackvault.com/documents/cia/ufos/C05515622.pdf

https://was-pywb-prod.stanford.edu/was/20211109205457/https://www.theblackvault.com/documentarchive/ufos-the-central-intelligence-agency-cia-collection/

**Comment by peterchanws** [comment]
This example show site not rending at all in openwayback but rendered properly in pywb

https://swap.stanford.edu/20120218112734/http://www.aldemokrati.org/
https://was-pywb-prod.stanford.edu/was/20120218112734/http://aldemokrati.org/

**Comment by peterchanws** [comment]
Crawl missing from openwayback appear in pywb (mentioned in another issue, put it here to make this issue more complete)

Captured 12 times
https://swap.stanford.edu/*/http://www.stanford.edu/~yesavage/

13 captures
https://was-pywb-prod.stanford.edu/was/*?url=http%3A%2F%2Fwww.stanford.edu%2F~yesavage%2F

**Comment by mjgiarlo** [comment]
Peter C feels like this is now done. Closing.
