### ISSUE TITLE
Playback performance testing

### ISSUE THREAD

**Issue by edsu** [sul-dlss/was-pywb#15]
Once the full data is available on was-pywb-prod we should do some performance testing to see what the response times are like. It's possible a tool could do this, or a program that is able to do concurrent requests would work as well. Ideally we would put it under load with a set of URLs, and generate average, min and max response times. It would be useful to point it at the existing openwayback at swap.stanford.edu to serve as a baseline. While the test is running it will be useful to interact with the server in the browser to see what the user experience is like, and to keep an eye on system utilization using `htop` on was-pywb-prod.

**Comment by mjgiarlo** [comment]
Interactions to test:

* Homepage
* List of 1,000 URLs to test (@edsu to share here) in parallel
* Page w/ list of captures (note: this involves JavaScript)

**Comment by edsu** [comment]
Here is [urls.txt](https://app.zenhub.com/files/490957089/a4d3ac9d-fcb7-4213-a880-5aa7c60629ec/download) which is a list of a 1000 URLs that should be present in the archive.

I'm also attaching [bench.rb](https://app.zenhub.com/files/490957089/940d3ded-0f55-4c59-af9b-562f2ebebf24/download) which I used previously to stress test the CDX API (used by the pywb user interface from JavaScript). It might be useful as a starting point for a stress test. Lets commit whatever gets used to the `bin` directory for future stress testing if it's needed.

**Comment by edsu** [comment]
These figures are encouraging! How many concurrent requests were you running?

**Comment by aaron-collier** [comment]
@edsu for these results, 10 concurrent processes in all cases, so in the second example, 30 at a time doing 3 different things. I can set that to whatever we wish, just testing the playback urls i was able to do 100 concurrent before I didn't see any average gain but haven't run all 3 with 100 concurrent yet.

**Comment by edsu** [comment]
That should be sufficient I think! There's no need to do more unless you are curious to see what happens.

**Comment by edsu** [comment]
@aaron-collier In case it's useful here's a list of 100K URLs :-) 

[urls.txt.gz](https://github.com/sul-dlss/was-pywb/files/8951926/urls.txt.gz)
