### ISSUE TITLE
SearchWorks linking

### ISSUE THREAD

**Issue by edsu** [sul-dlss/was-pywb#16]
We need to ensure that links from SearchWorks to swap.stanford.edu continue to work. For example the links on this page:

https://searchworks.stanford.edu/view/xr213rf3985

[sul-embed](https://github.com/sul-dlss/sul-embed/blob/master/app/models/embed/was_time_map.rb) currently uses SWAP's Memento API to determine what archive snapshots are available for a URL in order to display them. Since pywb also has a Memento API (already confirmed enabled), this should continue to work, hopefully with very little adjustment.

Since we will have an intervening collection `swap.stanford.edu/{collection-name}/` we will also want to set up a permanent redirect in Apache so that anyone who has created links to swap.stanford.edu will have them continue to work.

There is some analysis work that needs to be done to figure out how to test this prior to launch.

**Comment by lwrubel** [comment]
Current OpenWayback TimeMap API used by sul-embed: swap.stanford.edu/timemap/<seedurl>

was-pywb's TimeMap API: was-swap-prod.stanford.edu/was/timemap/link/<seedurl>

More info in [pywb's documentation](https://pywb.readthedocs.io/en/latest/manual/memento.html#timemap-api)

**Comment by mjgiarlo** [comment]
Mike will talk to Access team about how best to time and coordinate and test this change.

**Comment by mjgiarlo** [comment]
Differences in timemaps to determine if they are breaking or not:

* The `@rel="self"` link lacks an `until=` value in pywb
* pywb has the same `@rel="memento"` links but does not mark the first and last of these with `@rel="first memento"` or `@rel="last memento"`

**Comment by edsu** [comment]
It looks like this is redirecting properly now, and once swap.stanford.edu points at was-pywb-prod sul-embed will be pointed in the right direction:

```
➜  was-pywb git:(t71-rel-paths) ✗ curl -i https://was-pywb-prod.stanford.edu/timemap/https://news.stanford.edu
HTTP/1.1 301 Moved Permanently
Date: Mon, 27 Jun 2022 14:01:06 GMT
Server: Apache/2.4.41 (Ubuntu)
Strict-Transport-Security: max-age=31536000; includeSubDomains
Location: https://was-pywb-prod.stanford.edu/was/timemap/link/https:/news.stanford.edu
Content-Length: 284
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://was-pywb-prod.stanford.edu/was/timemap/link/https:/news.stanford.edu">here</a>.</p>
</body></html>
```

It looks like sul-embed's [use of Faraday](https://github.com/sul-dlss/sul-embed/blob/305b3c12924a3de19040e8c96f3335e9e26ce013/app/models/embed/was_time_map.rb#L18) does not follow redirects?

```
irb(main):002:0> r = Faraday.get('https://was-pywb-prod.stanford.edu/timemap/htt
ps://news.stanford.edu')
=>
#<Faraday::Response:0x00007f9f588b8090
...
irb(main):003:0> r.status
=> 301
```

Maybe we can send a PR for that?

**Comment by mjgiarlo** [comment]
These are the URLs I've been using to test in stage:

* https://argo-stage.stanford.edu/view/druid:fg981bn7530
* https://sul-purl-stage.stanford.edu/fg981bn7530 (embed appears to render fine and link to was-pywb-stage)
* https://searchworks-preview-stage.stanford.edu/view/fg981bn7530 (embed does not render)

**Comment by mjgiarlo** [comment]
@edsu 💬 
> It looks like sul-embed's [use of Faraday](https://github.com/sul-dlss/sul-embed/blob/305b3c12924a3de19040e8c96f3335e9e26ce013/app/models/embed/was_time_map.rb#L18) does not currently follow redirects?
> [...]
> Maybe we can send a PR for that?

I'll chat with Chris. Good eye!

**Comment by mjgiarlo** [comment]
> These are the URLs I've been using to test in stage:
> 
> * [argo-stage.stanford.edu/view/druid:fg981bn7530](https://argo-stage.stanford.edu/view/druid:fg981bn7530)
> * [sul-purl-stage.stanford.edu/fg981bn7530](https://sul-purl-stage.stanford.edu/fg981bn7530) (embed appears to render fine and link to was-pywb-stage)
> * [searchworks-preview-stage.stanford.edu/view/fg981bn7530](https://searchworks-preview-stage.stanford.edu/view/fg981bn7530) (embed does not render)

I believe the SW-preview-stage instance isn't rendering due to that service pointing at prod PURL (vs. stage PURL). It's using this default config: https://github.com/sul-dlss/SearchWorks/blob/master/config/settings.yml#L20 (Not overridden in shared_configs: https://github.com/sul-dlss/shared_configs/blob/searchworks-preview-stage/config/settings/production.yml). See related HB alert: https://app.honeybadger.io/projects/50022/faults/38378660

**Comment by mjgiarlo** [comment]
I've fixed up ☝🏻 by making some puppet and shared_configs changes to SearchWorks, and it now appears SearchWorks linking is now working as expected in stage. See https://sul-purl-stage.stanford.edu/fg981bn7530 & https://searchworks-preview-stage.stanford.edu/view/fg981bn7530 as evidence. 

The last bit of work will be expanding the sul-embed service to allow dereferencing timemaps through redirects: https://github.com/sul-dlss/sul-embed/pull/1344 When that PR gets merged, this issue will be closed. So I think there's no more work to be done here.

**Comment by edsu** [comment]
Looks good, thanks for wrangling the various aspects of this @mjgiarlo!
