### ISSUE TITLE
Docker: Nginx -> Apache for local development

### ISSUE THREAD

**Issue by edsu** [sul-dlss/was-pywb#17]
For parity the Docker Compose setup should use Apache for development instead of Nginx so that we can notice any problems (hopefully none) sooner. This will likely involve creating an Apache config file, which ideally should be similar to what runs in stage/qa/prod?

**Comment by ndushay** [comment]
This is about the stage environment;  the production environment is already apache.

**Comment by edsu** [comment]
Actually this is just about the local development environment (Docker Compose). Prod, Stage and QA (once it is up) are all Apache.

**Comment by edsu** [comment]
I was kind of wondering if we might want to simplify this repository by making it just contain a dev setup for running pywb under uwsgi instead of apache or nginx in front of uwsgi. The actual Apache configuration being used in qa/stage/prod lives elsewhere in puppetland and wouldn't really be tested at all here.

Yes, I'm contradicting the person who created the ticket (myself).

**Comment by justinlittman** [comment]
@edsu My python has gotten a little rusty, but isn't the Dockerfile using straight uwsgi? https://github.com/sul-dlss/was-pywb/blob/main/Dockerfile#L34

**Comment by justinlittman** [comment]
Oh, I see where nginx is now.
