### ISSUE TITLE
Deploy with Capistrano

### ISSUE THREAD

**Issue by edsu** [sul-dlss/was-pywb#2]
While we can use Docker for development we don't have Docker in our Stage or Production environments (yet), but we will need to deploy pywb to those environments. It ought to be possible to use Capistrano to deploy pywb, which would allow us to use other SDR tooling (sdr-deploy) to manage it over time.

This work is dependent on the provisioning of *was-pywb-prod* and *was-pywb-stage*.

**Comment by ndushay** [comment]
@aaron-collier can you pls comment in the ticket why this is no longer ready?  Is there a blocking task we need to capture on the board in some way?

**Comment by edsu** [comment]
pywb recommends uwsgi for deploymentbecause that's a popular tool with the Python community, and I think it has mostly been tested using that. But it sounds like in theory it could work under Passenger, which might be more familiar to DLSS landscape?

https://www.phusionpassenger.com/library/walkthroughs/basics/python/fundamental_concepts.html

**Comment by ndushay** [comment]
I'm unassignig Aaron now that this is ready.  He can pick this up again if he wants.

**Comment by edsu** [comment]
I'm happy to pair with whoever is available to try to figure out what this might look like.
