### ISSUE TITLE
Hook up CircleCI

### ISSUE THREAD

**Issue by edsu** [sul-dlss/was-pywb#22]
Now that there are some tests it would be good to have CircleCI run them.

**Comment by mjgiarlo** [comment]
Feel free to use #25 if helpful, even if the CircleCI config there is not working, or not. Throw it away if not.

**Comment by edsu** [comment]
Thinking some more about this, perhaps we don't really need was-py tests and to run them in CircleCI if we are going to have an integration test in https://github.com/sul-dlss/infrastructure-integration-test/issues/434 ?

**Comment by edsu** [comment]
I think all CircleCI needs to do is:

1. bring up the the docker-compose environment
2. run `docker compose exec pywb bundle exec rake`

Which ought to be doable?

**Comment by mjgiarlo** [comment]
Could be https://github.com/sul-dlss/was-pywb/pull/25 is overly complicated and what you write above will totally suffice.
