### ISSUE TITLE
Images missing in production but appear in stage

### ISSUE THREAD

**Issue by peterchanws** [sul-dlss/was-pywb#224]
I have the same wacz in stage and production showing different view - image missing in production but appear in stage. 
https://swap-stage.stanford.edu/was/20231106200536/https://eastwindezine.com/how-to-write-a-short-story-a-charlie-chin-story/
https://swap.stanford.edu/was/20231106200536/https://eastwindezine.com/how-to-write-a-short-story-a-charlie-chin-story/

Here are the event list: I started a crawl in my office computer on Nov. 6. It didn't finished when I left office. I uploaded the wacz file on Nov. 9 - size of the crawl is 32.4 GB https://argo-stage.stanford.edu/view/druid:rp301bg0615. I started another crawl at home on Nov. 8. The crawl size is 8.61 GB https://argo-stage.stanford.edu/view/druid:cm018hs4029. I uploaded the 32.4 GB wacz file to production because the creator cannot access our stage environment.

<img width="1638" alt="Screenshot 2023-11-17 at 8 23 34 AM" src="https://github.com/sul-dlss/was-pywb/assets/1050899/a896141c-fbd8-46c8-891c-c99a084a7631">
<img width="1630" alt="Screenshot 2023-11-17 at 8 24 08 AM" src="https://github.com/sul-dlss/was-pywb/assets/1050899/2abeece5-bcd8-4257-a5e7-efdac6eb4496">

**Comment by andrewjbtw** [comment]
@peterchanws Were you able to fix this? I see that the images now appear at the link to the prod view above.

**Comment by peterchanws** [comment]
Thanks, Andrew, for letting me know. I have no idea when they were fixed. We will make a final crawl by end of this year. Hope we have the same result at that time.
