### ISSUE TITLE
Indexing errors

### ISSUE THREAD

**Issue by edsu** [sul-dlss/was-pywb#26]
While doing #13 and running on our production data I noticed that [cdxj-indexer](https://pypi.org/project/cdxj-indexer/) can sometimes throw an error which results in a zero length CDXJ file being written. This has happened for 75 WARC files out of 32,714 (so far). For example:

```
was@was-dev:~$ cdxj-indexer --sort --post-append /web-archiving-stacks/data/collections/jt898xc8096/fq/567/wq/8955/ARCHIVEIT-5425-MONTHLY-JOB292430-20170430083101595-00035.warc.gz > x
Traceback (most recent call last):
  File "/opt/app/was/.local/bin/cdxj-indexer", line 8, in <module>
    sys.exit(main())
  File "/opt/app/was/.local/lib/python3.8/site-packages/cdxj_indexer/main.py", line 477, in main
    write_cdx_index(cmd.output, cmd.inputs, vars(cmd))
  File "/opt/app/was/.local/lib/python3.8/site-packages/cdxj_indexer/main.py", line 492, in write_cdx_index
    indexer.process_all()
  File "/opt/app/was/.local/lib/python3.8/site-packages/cdxj_indexer/main.py", line 210, in process_all
    super().process_all()
  File "/opt/app/was/.local/lib/python3.8/site-packages/warcio/indexer.py", line 33, in process_all
    self.process_one(fh, out, filename)
  File "/opt/app/was/.local/lib/python3.8/site-packages/cdxj_indexer/main.py", line 244, in process_one
    for record in wrap_it:
  File "/opt/app/was/.local/lib/python3.8/site-packages/cdxj_indexer/bufferiter.py", line 49, in buffering_record_iter
    join_req_resp(req, resp, post_append, url_key_func)
  File "/opt/app/was/.local/lib/python3.8/site-packages/cdxj_indexer/bufferiter.py", line 103, in join_req_resp
    method = req.http_headers.protocol
AttributeError: 'NoneType' object has no attribute 'protocol'
```

It looks like running without `--post-append` results in no error, so there must be something in the logic when that is being used which is causing this error. We should ticket the problem with [cdxj-indexer](https://pypi.org/project/cdxj-indexer/).

After indexing is complete we will need to locate these zero length CDXJ files, and reindex them either with a fixed cdxj-indexer or without `--post-append`. The new CDXJ files will then need to be merged into the larger index. Since `bin/index.rb` was designed to be run multiple times without regenerating CDXJ files that are already present on the filesystem it should be possible to delete the zero length files and rerun with the fix for `--post-append`. It may be possible to only merge the new files, or if it's easier they can all just be merged again.

**Comment by edsu** [comment]
I ticketed the issue in https://github.com/webrecorder/cdxj-indexer/issues/16 and will work on a small PR fix.

**Comment by edsu** [comment]
Note: some of the errors appear to be transitory, perhaps due to problems reading from the filesystem? I have been double checking some of the ones that show up in the console and they are not repeatable. For example this one was reported as an error but seems fine when retrying:

```
TMPDIR=/data/edsu/tmp cdxj-indexer /web-archiving-stacks/data/collections/kh149kf8484/sf/698/kg/9220/CDL-20140503180731-00072-grebe.ucop.edu-00482580.arc.gz
```

**Comment by edsu** [comment]
I also saw a fair number of these:

    Error -3 while decompressing data: invalid block type

I need to confirm whether they are warnings or they prematurely stopped indexing of a particular WARC file.

**Comment by lwrubel** [comment]
Confirm whether the fix for the Attribute Error is released in cdxj-indexer.

**Comment by edsu** [comment]
I've been testing with cdxj-indexer main (not yet released) and it seems to be working well.
