### ISSUE TITLE
was-pywb DevOpsDocs

### ISSUE THREAD

**Issue by edsu** [sul-dlss/was-pywb#32]
We need some documentation for was-pywb in https://github.com/sul-dlss/DevOpsDocs/tree/master/projects/web-archiving 

The openwayback docs can also be retired once we shut it down.

**Comment by mjgiarlo** [comment]
Important: in the pywb devopsdocs, please record that the backup strategy for pywb is to lean on the existing backups of the web archiving stacks via preassembly-prod. And that neither QA nor stage are backed up.
