### ISSUE TITLE
Current working directory for uwsgi

### ISSUE THREAD

**Issue by edsu** [sul-dlss/was-pywb#33]
When was-pywb is deployed to qa, stage and prod environments uwsgi is started up with a current working directory of something like:

    /home/was/swap/releases/20220614155217

pywb isn't able to find its template and static assets since it appears to be looking for them in directories relative to the current working directory, but they are one level down in: 

    /home/was/swap/releases/20220614155217/pywb

Either pywb needs to be convince to look for them in the right place using its configuration file (config.yaml), preferably at:

    /home/was/swap/releases/current/pywb

or we need to start uwsgi with that as its current working directory.

**Comment by mjgiarlo** [comment]
@edsu This has now been applied in prod.
