### ISSUE TITLE
Ensure pywb's ACLJ file is backed up

### ISSUE THREAD

**Issue by edsu** [sul-dlss/was-pywb#42]
It should be possible for us to keep the pywb's configuration `config.yaml` in Git, and to deploy from there. However the ACLJ file used for controlling pywb's access to URLs needs to be updated automatically based on rights changes in Argo (see #10). 

We need to ensure that this ALCJ file is being regularly backed up in production. Probably the easiest way to do that is to store it in a location that is already backed up, e.g. /web-archiving-stacks/ ?

**Comment by mjgiarlo** [comment]
And record this in DevOpsDocs.

**Comment by mjgiarlo** [comment]
Any ACL files written to the web archiving stacks will be backed up as this NFS mount is already backed up on preassembly-prod. Closing.
