### ISSUE TITLE
Dependency updates

### ISSUE THREAD

**Issue by edsu** [sul-dlss/was-pywb#43]
In an ideal world our weekly dependency updates would check to make sure that any Ruby or Python dependencies in was-pywb are kept up to date as in other projects. The Ruby ones should (hopefully) be easy since we have a functionality for that already. But the Python ones may require some work in [access-update-scripts](https://github.com/sul-dlss/access-update-scripts) or elsewhere?

**Comment by mjgiarlo** [comment]
AFAICT, every time we deploy was-pywb, we run `pip3 install -r requirements.txt` which---given we haven't pinned any of the app's dependencies to particular versions---should always result in running the app on the latest matrix of dependencies that work together. So I don't think we need any access-update-scripts work. I'll document this in the README.
