### ISSUE TITLE
Google Analytics track archived web site being accessed

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/was-pywb#44]
If it's possible somehow to pass along the archived web site that is being accessed in the URL that would be awesome, but it's not essential at this point.

For example if when tracking access to a page like:

    https://swap.stanford.edu/20180323165336/https://graphics.stanford.edu/talks/DigMich-UVa-oct05/DigMich-UVa-19oct05-san_files/v3_document.htm

It would be nice to also be able to tell Google Analytics that `graphics.stanford.edu` was being viewed somehow. I'm not even sure if that's possible, but it might be?

**Comment by justinlittman** [comment]
Any guidance / information on Google Analytics? I literally know nothing about it or our use of it in SWAP.

**Comment by lwrubel** [comment]
@aaron-collier did the work to add our tracking code to SWAP already and it's in GA as the property, "Stanford Web Archive Portal (SWAP)" > "SWAP activity". If you don't already have access to Google Analytics, @anarchivist could help. This is just a start, happy to look at GA together, and @edsu may have further ideas here.

**Comment by lwrubel** [comment]
@edsu @peterchanws I am wondering if we should pull this one back. I'm not sure that GA configuration is available to get us closer towards this, but it is possible to see page usage using an export of GA data. 

We can already use Behavior > Site Content > All Pages to get all pages' view counts and then further filter that using an advanced filter with a regex with `http`. You can then export that report, split the URLs column out by `://` (noting that will leave out some early data when the apache redirects were dropping slash) and then use a pivot table to roll up the number of views. That can get you something like this: https://docs.google.com/spreadsheets/d/1HCOQ_xd3BtOxQsc5ttqlW4yeb9r8Csy2-bIZClMYAmg/edit#gid=90735054

Would that be useful enough?

**Comment by peterchanws** [comment]
I show a bibliographer using Google Analytics to track the usage of her collection (seed level). I have no idea how to use an export of GA data. I guest Google Analytics would be easier for non-technical like me and other bibliographers.

**Comment by peterchanws** [comment]
I checked our swap.stanford.edu in May and can see visit activities. However, when I check again today, nothing show for last 12 months:
https://analytics.google.com/analytics/web/?utm_source=marketingplatform.google.com&utm_medium=et&utm_campaign=marketingplatform.google.com%2Fabout%2Fanalytics%2F#/p312197778/reports/reportinghub?params=_u.dateOption%3Dlast12Months%26_u.comparisonOption%3Ddisabled

I remember we use swap.stanford.edu before our moving to pywb. Now, the url is https://swap.stanford.edu/was/. Would this affect the report?

**Comment by edsu** [comment]
I'm noticing that Google is [changing](https://support.google.com/analytics/answer/11583528) how they collect analytics and SUL is still using the previous method. Any research and customization that we do now would need to be ported forwards to the new method. 

Also, anything that we change now in how analytics are collected will only effect data that is collected in the future, and will not change the data that has been previously collected. So it won't help Zhaohui in her research.

However, the method that @lwrubel mentions above would be a good way to extract host level and page level information about archives that have been accessed. We can help do that in the future when needed, just open a ticket or ask us in Slack.

**Comment by lwrubel** [comment]
@peterchanws I was able to view May data for the old SWAP. Maybe your session expired or something else was going on when you were trying to view the older data? Nothing should be deleted from GA.

**Comment by peterchanws** [comment]
@lwrubel I can see them now.
