### ISSUE TITLE
Apache redirects

### ISSUE THREAD

**Issue by edsu** [sul-dlss/was-pywb#47]
pywb adds a collection name `was` to the URL for archived web content. For example: 

    https://swap.stanford.edu/20170823182220/http://www.azyz.org/

will become:

    https://swap.stanford.edu/was/20170823182220/http://www.azyz.org/

In order for links to archived content in swap.stanford.edu to continue to work after the deployment we should have Apache rewrite these URLs with a 301 Permanent Redirect.

Ideally it would be possible to test this with the was-pywb Docker setup if #17 is done. But the config will likely need to live with [Puppet](https://github.com/sul-dlss/puppet) and/or [shared_configs](https://github.com/sul-dlss/shared_configs/).

**Comment by mjgiarlo** [comment]
This is done.
