### ISSUE TITLE
Add "https://" in front of search bar

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/was-pywb#49]
As recommended by @astridu from user testing, add "https://" in front of the search bar. This is like the current SWAP interface. It does not affect pywb CDXJ lookups if the user enters http://, https:// or no prefix. 

<img width="1159" alt="image (1)" src="https://user-images.githubusercontent.com/1619369/174827312-fa07afb1-4cd4-4dda-8d9a-fc17c0de16fd.png">

Other tickets will address further wording and design changes on the home page.

**Comment by peetucket** [comment]
I presume while editing this page, I should also replace the "Collection was Search Page" banner with the banner that is currently on the home page ("Stanford's Wayback Machine") since the home page is going away with the redirects in #47

**Comment by peetucket** [comment]
And change "Search the was collection..." to "Search the collections..."

**Comment by lwrubel** [comment]
#51 will get into the wording and other resources that might need to be added to this new "home" page. So it's fine to change the wording for now, we'll get it right later.
