### ISSUE TITLE
Use 'was' collection page as pywb homepage

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/was-pywb#51]
Requires discussion with @astridu, @peterchanws, and @andrewjbtw about example visual designs and any sites or other resources to be included on the home page.  Astrid will provide designs.

**Comment by mjgiarlo** [comment]
@andrewjbtw and @peterchanws will meet with @astridu to decide what design we'll go with.

**Comment by edsu** [comment]
Part of this is complete now that requests for the home page redirect to `/was/` see https://github.com/sul-dlss/operations-tasks/issues/3074

**Comment by aaron-collier** [comment]
Is this closable now that `https://was-pywb-prod.stanford.edu/` redirects to `https://was-pywb-prod.stanford.edu/was/`? Or is there more to this ticket?

**Comment by mjgiarlo** [comment]
@aaron-collier I wonder if we should close this issue and if there are specific tweaks we want made to this page (thinking about visual design, textual elements, etc.), we should ticket that separately. That sound reasonable, @edsu ?

**Comment by mjgiarlo** [comment]
Closing per discussion.

**Comment by edsu** [comment]
Yes, I'm fine with this as long as we don't forget that somebody needs to decide if the homepage is ok as part of this work cycle. Having an open issue is usually a good reminder for me.

**Comment by mjgiarlo** [comment]
@edsu I'll write up a new issue, np
