### ISSUE TITLE
Add previous / next capture links to banner 

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/was-pywb#52]
First up, do analysis to figure out how to do this in pywb.

Current SWAP has links to previous and past captures from the header:

![Screen Shot 2022-06-21 at 10 49 36 AM](https://user-images.githubusercontent.com/1619369/174829686-9cae7d0a-80ff-4aa5-89e2-9fb63f62b221.png)

Per @astrid's user testing conversations, having these in pywb would be useful. This needs research to determine whether there is an existing option to turn these on and if not, how to get the data to present them. For example, it may be possible to use the [CDXJ API ](https://pywb.readthedocs.io/en/latest/manual/cdxserver_api.html )to get nearby capture dates. 

Mockup from Astrid:
<img width="866" alt="image (2)" src="https://user-images.githubusercontent.com/1619369/174829675-1b2477ea-5e5c-4800-bd56-a08ad47f4c4c.png">

**Comment by aaron-collier** [comment]
Note, there is an open issue on webrecorder/pywb for this feature: https://github.com/webrecorder/pywb/issues/506. I will continue to look into building this ourselves using the API.

**Comment by aaron-collier** [comment]
@edsu / @lwrubel - The good news is I figured out how to get a previous/next url from the cdxj api! It's not the prettiest javascript, but I'll work on refactoring tomorrow.

I'm not certain this is a viable solution for sharing upstream vs. something that gets these values into the metadata, so we may want to discuss that as a next/different step.

**Comment by edsu** [comment]
Awesome! I think you're right to focus on getting it working for us first -- then if it can be packaged up for upstream we can open that as a separate issue, maybe for in between work cycles?

**Comment by edsu** [comment]
@aaron-collier if you are looking for any design on this @astridu dropped this into Slack a week or so ago, and I forgot to add to this issue:

<img width="866" alt="image" src="https://user-images.githubusercontent.com/33829/176533949-36b1f26f-4799-4b1c-bc76-3c5cb745761b.png">

Astrid decided to go w/ "archival" gray instead of the Cardinal Red.

**Comment by astridu** [comment]
Hex: 53565A (gray from our palette)

**Comment by ndushay** [comment]
this was discussed this morning ... @lwrubel or @mjgiarlo can you add a comment here indicating what is needed now?

**Comment by mjgiarlo** [comment]
@ndushay 💬 
> this was discussed this morning ... @lwrubel or @mjgiarlo can you add a comment here indicating what is needed now?

https://github.com/sul-dlss/was-pywb/pull/80#issuecomment-1176432377
