### ISSUE TITLE
Test advanced search

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/was-pywb#58]
Further tickets may come out of this testing, depending on what @peterchanws might identify as useful to change / clarify / improve.

**Comment by edsu** [comment]
@peterchanws Interesting--can you copy/paste the URL that you used for your search on was-pywb-prod?

**Comment by peterchanws** [comment]
https://was-pywb-prod.stanford.edu/was/*?url=http%3A%2F%2Fwww.stanford.edu%2F~yesavage%2F&from=2015&to=2019

The missing [December 11th, 2016 at 14:41:49] capture in swap exist in Archive-It 
https://wayback.archive-it.org/5591/20160501000000*/http://www.stanford.edu/~yesavage/ACRC.html

So, I think it is a problem with the existing openwayback.

**Comment by mjgiarlo** [comment]
We think we should add some UI hints to make it easier for users to figure out how to enter dates for search.

**Comment by mjgiarlo** [comment]
We would also like for Astrid to take a look at this when she has time.

**Comment by edsu** [comment]
This pywb issue is also relevant https://github.com/webrecorder/pywb/issues/729

**Comment by mjgiarlo** [comment]
We think we can close this issue and if we desire advanced search changes in the future, those will be ticketed separately.
