### ISSUE TITLE
SLAC websites from 1990s should render at original URLs

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/was-pywb#60]
The SLAC early websites were added to openwayback and made replayable at close-to-original URLs by editing the CDX indexes to point to the WARC content as created using wget on a filesystem.  The early SLAC websites need to be made findable/replayable in pywb. Ideally, this is done NOT by editing the CDXJ files, since those edits would get lost if re-indexing occurs. 

In SWAP, the CDX was edited to use the original-ish URLs (we are not sure if the original hostname included "slacvm"). The capture date was changed to the "last modified" date on the file. The URLs used for replay are not in the WARC records themselves (but are in the HTML). The offset in the index gets SWAP to the WARC record to be rendered at the URL in the index. 

Example CDX lines from SWAP:
```
slacvm.slac.stanford.edu/find/wwwinfo.html 19930607000000 http://slacvm.slac.stanford.edu/FIND/wwwinfo.html text/html 200 QICRPKEGY6ZRQFBIYEKVKCVQGECHCBP7 - - 962231 SLAC_1993.warc
slacvm.slac.stanford.edu/find/xwhere.html 19920818000000 http://slacvm.slac.stanford.edu/FIND/xwhere.html text/html 200 YHAEO6T32AMDV24UH76XWWBXBRDC3AJX - - 321140 SLAC_1993.warc
```

When the WARCs were re-indexed for pywb using cdxj-indexer, we do not have the original URL or "capture" dates, just the WARC-Target-URI that shows a filesystem path, and the capture date from the wget process (2014), stored in WARC-Date. 

One approach would be to create a version of the WARCs to be used for replay, while keeping copies of the WARCs created in 2014. The edited WARCs would have their headers and Target-URIs edited to match the replay URLs, using [guidance for WARC Provenance Headers](https://labs.rhizome.org/presentations/warc-proposals.html#/1)

* WARC-Date moved to the new field WARC-Capture-Date
* WARC-Date is populated with the 1990s date in the CDX used by SWAP
* Target-URI edited to the URL used in the CDX. This will take some investigation to figure out how to match these up. 

The warcio python library is one tool that could be used for editing WARCs. One the edited WARCs are prepared, they can be indexed. 

[Argo record for SLAC WARCs](https://argo.stanford.edu/view/druid:wx794kg1767).

**Comment by edsu** [comment]
I'll admit, I was initially skeptical that `slacvm.slac.stanford.edu` was the correct original host name (vms in 1990?). I thought maybe it was some artifact of hosting the original files on a virtual machine for wget to collect and convert to WARZC. But I discovered [this paper](https://www.slac.stanford.edu/welcome/slac-pub-763.html) by Jean Marie Deken (SLAC Archivist) that she presented at the Society of American Archivists in 1997, which has as a reference to slacvm that seems to corroborate it.

**Comment by mjgiarlo** [comment]
Solution: produce derivative WARCs based on originals to edit headers (see above) such that they render like 1990s WARCs and then accession a new SDR version.

**Comment by mjgiarlo** [comment]
@edsu is inclined to pick this up. Leaving in backlog for now.

**Comment by edsu** [comment]
I'm working over in this repository on the WARC rewriting, since it doesn't really fit in the was-pywb repo.

https://github.com/sul-dlss-labs/slac-warc

**Comment by edsu** [comment]
Over in the [slac-warc](https://github.com/sul-dlss-labs/slac-warc) I wrote a program that creates a new WARC file `SLAC_rewrites.warc` using information from our OpenWayback CDX index when the date and URL in the index is different from the WARC-Target-URI and WARC-Date in the WARC data.

The idea is to then index the existing WARC data as is along with this new file `SLAC_rewrites.warc` which should also be added to a new version of [druid:wx794kg1767](https://argo.stanford.edu/view/druid:wx794kg1767) preferably with information about how it was created perhaps using the [README.md in slac-warc](https://github.com/sul-dlss-labs/slac-warc/blob/main/README.md)?

**Comment by lwrubel** [comment]
The detailed description in the slac-warc README was really helpful in understanding more about the WARCs and how they were indexed, @edsu. Good catch about some of the internal links not having been added to the CDX files. How do we handle the situation where there are multiple CDX entries for a WARC--we're duplicating the records? 

How do you recommend testing playback?

**Comment by andrewjbtw** [comment]
I'm less concerned with whether this is a new item or not than with whether it's possible to create new versions of webarchive-binary content. We need to be able to do that.

**Comment by edsu** [comment]
The existing SLAC content was indexed on prod (into `level0.cdxj`), and the newly created `SLAC_2022.warc` (with the modified dates and URLs that preserve the CDX index changes that were made in 2014) has been registered as [druid:tx739ch3649](https://argo.stanford.edu/view/druid:tx739ch3649). The data made it through the workflow so these seeds are now viewable again:

* https://searchworks.stanford.edu/view/fm065cw5306
* https://searchworks.stanford.edu/view/cj553qq9651
* https://searchworks.stanford.edu/view/qs852wh8529

If we decide that the documentation from [slac-warc](https://github.com/sul-dlss/slac-warc) should be added to druid:tx739ch3649 we can create a new issue for that.
