### ISSUE TITLE
Improve style / display of homepage

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/was-pywb#76]
On June 29th, @astridu, @peterchanws, and @andrewjbtw will talk through the visual design of the current was-pywb homepage (which is the `was` collection page since our instance has but a single collection). This issue is to collect changes to this page, whether they be stylistic (colors, fonts, positions, etc.) or content-based (new links, new text, changed labels).

Once the changes have been collected and decided upon, we should divide them into ones that are critical---*i.e.*, the ones that we want to BLOCK switch-over of SWAP to was-pywb in production---and ones that needn't block the production switch. (This does not mean they will not be done.)

**Comment by peterchanws** [comment]
Please use the following for featured collections:

Chinese Non-Governmental Organizations Web Archive
https://searchworks.stanford.edu/view/jt898xc8096

Freedom of Information (FOIA)
https://searchworks.stanford.edu/view/bs665fm2060

SLAC Earliest Websites
https://searchworks.stanford.edu/view/wk956yb8565

Stanford University Websites
https://searchworks.stanford.edu/view/xs048zp7815

**Comment by peterchanws** [comment]
Design from Astrid:

Web archive portal home: 
https://invis.io/FV12SVON7CSA#/468101257_home_5

Example of gray banner on archived site: 
https://invis.io/FV12SVON7CSA#/468101027_banner

**Comment by edsu** [comment]
I think the main focus of this is to get the logical units in place on the page, and if the background images are possible that would be good, but is not essential. If you want to experiment @astridu supplied this background image:

![header](https://user-images.githubusercontent.com/33829/176682370-e9c5cd98-1dc9-4518-b7f5-1e23cadc248b.png)

**Comment by aaron-collier** [comment]
@astridu do you have the specs (font-size, etc) for the mock ups? Thanks.

**Comment by astridu** [comment]
I put the font sizes in here. Do you need anything else?
https://invis.io/FV12SVON7CSA#/468101257_home_5
