### ISSUE TITLE
Header also displays inside frame occasionally

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/was-pywb#86]
pywb is showing the red Stanford header inside the frame as well. 

![Screen Shot 2022-07-05 at 7 17 01 PM](https://user-images.githubusercontent.com/1619369/177432262-f3ea61f8-685c-4eab-ac07-a6240f8ecd91.png)

**Comment by lwrubel** [comment]
See also: https://swap.stanford.edu/was/20160827002355/http://artgoldhammer.blogspot.com/
![Screen Shot 2022-07-06 at 4.34.51 PM.png](https://images.zenhubusercontent.com/61d8318383f9e3f0e199b693/2bd8be9e-c0fa-4c59-8673-cd8a262e01be)

**Comment by mjgiarlo** [comment]
Both of the instances above look like the original site may have had embedded `iframe`s? Or perhaps I'm misunderstanding what's going on.

**Comment by aaron-collier** [comment]
@lwrubel I'm unable to reproduce the first screen shot. When not found I get "0 results" and the page looks fine. If you can reproduce, can you send me the link? Thanks.

**Comment by aaron-collier** [comment]
I believe this is an issue with the captured pages html and/or javascript (though I'm not sure how to look at that individually - maybe unpacking a wacz file or something?)

You can see here that the top `#document` is the main page. For the pages that exhibit this behavior, there is a second `#document` which indicates, to me, that pywb is inserting somewhere and the captured pages have an unexpected selector that happens to match.

I'm not sure we can fix this locally, it likely has to be addressed upstream. I'd be happy to open a ticket there if we wish.

![Screen Shot 2022-07-07 at 11 29 19 AM](https://user-images.githubusercontent.com/2294288/177844439-2d74858e-e71a-426d-806f-a24e00173f7f.png)

**Comment by aaron-collier** [comment]
It may be as simple as pywb selecting an `iframe` on the page (and inadvertently selecting all iframes), so if a page has one we get this odd behavior... Or an iframe with a particular id/class...

https://github.com/webrecorder/pywb/blob/626da99899865e7f9bf9bfdd775218b36d6a2567/pywb/static/wb_frame.js#L58

**Comment by lwrubel** [comment]
Sorry about not including a URL for the first screenshot, @aaron-collier. I can't replicate that now, but here's another error page (don't worry about the particular error, that's an indexing issue):
https://swap.stanford.edu/was/20170706223605/http://enchantingthedesert.com/

**Comment by lwrubel** [comment]
I looked at the issue with error pages, and I'm coming to realize that one possible aspect of this is that we seem to be adding the `header.html` into all pages, including `frame_insert.html`. Other pywb instances are not adding the header on `frame_insert.html`. They're just putting a logo in the existing gray bar and possibly styling the color of it. The way we have this set up, the header displays twice because we're adding it in `base.html` and `frame_insert.html`.

See: https://www.webarchive.org.uk/wayback/archive/20130415225159/https://www.gov.uk/government/how-government-works
https://www.webarchive.org.uk/wayback/archive/*/https://www.bl.uk/

**Comment by lwrubel** [comment]
Based on conversation with @aaron-collier, we'll remove the header from `frame-insert.html`, see if we can get a logo in there at a minimum, and discuss with @peterchanws on 7/11/22.
