### ISSUE TITLE
Set <title> to title of replayed page

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/was-pywb#90]
We're setting the title tag to be static: "Stanford Web Archive Portal". Investigate whether/how pywb sets the title to reflect the page being replayed. See: https://pywb.readthedocs.io/en/latest/manual/ui-customization.html?highlight=title#templates as background. 

Openwayback appears to use the <title> contents from the replayed page.

**Comment by aaron-collier** [comment]
I'm seeing this on the page already.

![Screen Shot 2022-07-07 at 10.34.11 AM.png](https://images.zenhubusercontent.com/5cd34fcc78dbc64ff177a010/9d27eb6e-d0ac-4171-8c30-532480c09254)
