### ISSUE TITLE
SWAP homepage featured sites

### ISSUE THREAD

**Issue by peterchanws** [sul-dlss/was-pywb#91]
Here are the featured sites:

SLAC first web page
https://swap.stanford.edu/was/*/http:/slacvm.slac.stanford.edu/FIND/default.html
https://purl.stanford.edu/qs852wh8529

ShanghaiPRIDE
https://swap.stanford.edu/was/20170323182036/http://www.shpride.com/
https://purl.stanford.edu/dv443xj0944

Bureau of Alcohol, Tobacco, Firearms and Explosives (ATF) Freedom of Information Act (FOIA)
https://swap.stanford.edu/was/20170311062618/https://www.atf.gov/resource-center/freedom-information-act-foia
https://purl.stanford.edu/gf153xn2270

A Vision for Stanford
https://swap.stanford.edu/was/20180518001602/https://ourvision.stanford.edu/
https://purl.stanford.edu/fq241ty7810

Design from Astrid:

Web archive portal home:
https://invis.io/FV12SVON7CSA#/468101257_home_5

Example of gray banner on archived site:
https://invis.io/FV12SVON7CSA#/468101027_banner

**Comment by lwrubel** [comment]
@peterchanws would it be OK to go ahead with this without the slac website as a featured site and add that in when it's ready?

Also, could you add links to the druids for these sites' seeds? We could use the thumbnails for the homepage.

**Comment by peterchanws** [comment]
SLAC first web page
https://swap.stanford.edu/was/*/http:/slacvm.slac.stanford.edu/FIND/default.html
https://purl.stanford.edu/qs852wh8529

**Comment by lwrubel** [comment]
Added the SLAC link to the issue description above, all four sites are ready to be included.

**Comment by peterchanws** [comment]
@mjgiarlo Here is the updated links for
 
SLAC first web page
https://swap.stanford.edu/was/19911206000000/http://slacvm.slac.stanford.edu/FIND/default.html

ShanghaiPRIDE
https://swap.stanford.edu/was/20170323182036/http://www.shpride.com/

Bureau of Alcohol, Tobacco, Firearms and Explosives (ATF) Freedom of Information Act (FOIA)
https://swap.stanford.edu/was/20170311062618/https://www.atf.gov/resource-center/freedom-information-act-foia

A Vision for Stanford
https://swap.stanford.edu/was/20180518001602/https://ourvision.stanford.edu/

The purl links are here just for reference, not for the home page.

"What should the featured sites behavior be in our QA and staging instances?" 
I suggest to make them the same as prod - link out to prod
