### ISSUE TITLE
Links works in Archive-IT not working in pywb

### ISSUE THREAD

**Issue by peterchanws** [sul-dlss/was-pywb#98]
https://wayback.archive-it.org/8751/20220613070217/https://www.stanfordeugenics.com/
In the above archived site, I can click through "What is Eugenics?";"David Starr Jordan"; "Other Stanford Eugenicists"; "More"

However, these links don't work in our pywb environment:
https://swap.stanford.edu/was/20220613070141/https://www.stanfordeugenics.com/

Also, only one capture appears in Archive-IT on Jun3 13, 2022 (07:02:17). But, there are 2 captures in our SWAP: 2022-06-13 07:01:41 UTC and 2022-06-13 07:02:17 UTC

**Comment by edsu** [comment]
It's probably best to compare the same snapshots `20220613070217`

* https://wayback.archive-it.org/8751/20220613070217/https://www.stanfordeugenics.com/
* https://swap.stanford.edu/was/20220613070217/https://www.stanfordeugenics.com/

I think that pywb is doing a bit better at displaying the sub-menu items, which don't display at all at Archive-It. You can see these if you look at the live site:

https://www.stanfordeugenics.com/

But it appears the crawl is missing some JavaScript files that cause the menus not to be clickable in pywb. We could test this using a WACZ file (generated with ArchiveWeb.page) in QA?

**Comment by lwrubel** [comment]
I see this is a Wix site. As you probably know, @peterchanws, those can be tricky to capture. Do you know if it was captured with the [specific Archive-It settings for Wix](https://support.archive-it.org/hc/en-us/articles/208824546-Archiving-Wix-sites)?  it might be worth trying another AIT capture with those settings, unless this already reflects those being in place.

**Comment by peterchanws** [comment]
@lwrubel The capture was made without special settings. I encountered a Wix site which Archive-IT gave up and I captured it using webrecorder.

**Comment by edsu** [comment]
This seems related to #88 maybe we could start using a "playback" label to group these?

**Comment by edsu** [comment]
I downloaded the WACZ from https://argo-stage.stanford.edu/view/druid:cm752zx1126 and can confirm that the CDX file that comes in the WACZ is significantly different from the CDX file that `cdxj-indexer` generates. I still haven't dug into the details to characterize what the differences are, but it is clear from the number of lines in the file (bundled CDX has 433 lines and generated has 427). 

To further complicate matters when I used the CDX supplied with the WACZ in a test pywb collection it throws this error when attempting to load the content:

```python
{'args': {'coll': 'test', 'type': 'replay', 'metadata': {}}, 'error': '{"message": "Internal Error: \'int\' object has no attribute \'startswith\'"}'}
```

<img width="1772" alt="Screen Shot 2022-07-12 at 9 21 42 PM" src="https://user-images.githubusercontent.com/33829/178628205-925d881d-db58-41fa-9eb6-14963eed8e33.png">

**Comment by peterchanws** [comment]
Moved this example from #98.

https://wayback.archive-it.org/8751/20220613070217/https://www.stanfordeugenics.com/
In the above archived site, I can click through "What is Eugenics?";"David Starr Jordan"; "Other Stanford Eugenicists"; "More"

However, these links don't work in our pywb environment:
https://swap.stanford.edu/was/20220613070141/https://www.stanfordeugenics.com/
